// The Template / bind engine — the runtime the generated `view()` imports.
//
// A component compiles (phase 04) to a STATIC SKELETON plus a SLOT TABLE: the
// markup with its dynamic holes emptied, and, for each hole, where it lives
// (an element-child-index `path` from the clone root) and what it is (text /
// attribute / event / two-way / @if / @for). At runtime `view()` does:
//
//   1. instance()      — clone the skeleton into a fresh node tree;
//   2. bind_*_ctx(...)  — wire each slot to a reactive effect (vcsr.signal):
//                         reading a signal subscribes the slot, writing it
//                         re-runs ONLY that slot's patch — O(dependents), no
//                         diff, no virtual DOM;
//   3. view()           — hand back the live root.
//
// THIS FILE holds the backend-NEUTRAL surface (the slot table types + to_str) the
// generated code and both backends share. The rendering backend is selected at
// compile time by the `-d wasm_browser` flag:
//
//   • backend_native_notd_wasm_browser.v — default: an in-memory mock DOM, built
//     with vcsr's own parser, serialized by html() — testable without a browser.
//   • backend_wasm_d_wasm_browser.v      — `-d wasm_browser`: the real DOM via
//     host FFI, holding NO string-keyed maps and not running the V parser (both
//     of which fail on wasm — see docs/WASM-PATHS-ANALYSIS.md §2.1).
//
// Both expose the same Template.instance() / bind_*_ctx / Instance.view() / View,
// so the generated `view()` compiles unchanged against either. Build with
// -enable-globals (the effect stack is global).
module runtime

// SlotKind classifies a dynamic hole. Matches phase 02 / phase 04 exactly.
pub enum SlotKind {
	text  // an element's textContent follows an expression
	attr  // an attribute value follows an expression (`name`)
	event // a DOM event runs a handler (`name` = event, e.g. 'click')
	bind  // two-way: value follows an expression AND writes back on input
	cond  // @if: the element is present only while the expression is true
	list  // @for: a keyed list of rows
}

// SlotDesc locates one hole and says what it is. Emitted as a plain const by
// codegen, so every field is pub and the shape is frozen.
pub struct SlotDesc {
pub:
	kind SlotKind
	path []int  // element-child-index path from the clone root
	name string // attribute name (attr) or event name (event); else ''
}

// Template is a component's compiled form: the static skeleton + the slot table.
pub struct Template {
pub:
	html  string
	slots []SlotDesc
}

// to_str renders any bound value to text. Codegen wraps every text/attr/value
// expression in this, so it is a no-op on strings and correct for the scalar
// types bindings use (int/f64/bool). NOTE: a non-scalar operand (a struct/map)
// renders via V's autogenerated debug str() — a multi-line dump in the DOM. The
// intent is that bound expressions are string/numeric; richer types should be
// formatted in the component before binding (a future codegen type-check could
// enforce this).
pub fn to_str[T](v T) string {
	return '${v}'
}
