// counter.gen.v — GENERATED by vcsr. Do not edit.
// Plain V; imports only the vcsr runtime (no compiler builtins).
module main

import vcsr.runtime

const __counter_tpl = runtime.Template{
	html:  '<main class="counter">
  <h1></h1>
  <p class="muted">double <span></span></p>
  <button>+1</button>
</main>'
	slots: [
		runtime.SlotDesc{ kind: .text, path: [0] },
		runtime.SlotDesc{ kind: .text, path: [1, 0] },
		runtime.SlotDesc{ kind: .event, path: [2], name: 'click' },
	]
}

pub fn (mut c Counter) view() runtime.View {
	mut ins := __counter_tpl.instance()
	runtime.bind_text(mut ins, 0, fn [mut c] () string { return runtime.to_str(c.count.get()) })
	runtime.bind_text(mut ins, 1, fn [mut c] () string { return runtime.to_str(c.doubled()) })
	runtime.bind_event(mut ins, 2, fn [mut c] () { c.inc() })
	return ins.view()
}

pub fn (c Counter) style() string {
	return '/* Counter styles. Plain CSS; vcsr scopes these selectors to the Counter
   component at build time, so `.counter_fc0f33c3`/`.muted_fc0f33c3` can\'t collide with any other
   component. Tree-shaken if a class is never referenced by counter.html_fc0f33c3. */
.counter_fc0f33c3 {
  display: grid;
  gap: 0.5rem;
  padding: 2rem;
  max-width: 20rem;
}
.muted_fc0f33c3 {
  color: var(--muted, #888);
}
button {
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  cursor: pointer;
}
'
}
