// counter.gen.v — GENERATED by vcsr. Do not edit.
// Plain V; imports only the vcsr runtime (no compiler builtins).
module main

import vcsr.runtime

const __counter_tpl = runtime.Template{
	html:  '<main class="counter">
  <h1></h1>
  <p class="muted">double <span></span></p>
  <button>+1</button>
</main>'
	slots: [
		runtime.SlotDesc{
			kind: .text
			path: [0]
		},
		runtime.SlotDesc{
			kind: .text
			path: [1, 0]
		},
		runtime.SlotDesc{
			kind: .event
			path: [2]
			name: 'click'
		},
	]
}

fn counter_slot0_get(ctxp voidptr) string {
	mut c := unsafe { &Counter(ctxp) }
	return runtime.to_str(c.count.get())
}

fn counter_slot1_get(ctxp voidptr) string {
	mut c := unsafe { &Counter(ctxp) }
	return runtime.to_str(c.doubled())
}

fn counter_slot2_evt(ctxp voidptr) {
	mut c := unsafe { &Counter(ctxp) }
	c.inc()
}

pub fn (mut c Counter) view() runtime.View {
	mut ins := __counter_tpl.instance()
	runtime.bind_text_ctx(mut ins, 0, voidptr(&c), counter_slot0_get)
	runtime.bind_text_ctx(mut ins, 1, voidptr(&c), counter_slot1_get)
	runtime.bind_event_ctx(mut ins, 2, voidptr(&c), counter_slot2_evt)
	return ins.view()
}

pub fn (c Counter) style() string {
	return "/* Counter styles. Plain CSS; vcsr scopes these selectors to the Counter
   component at build time, so `.counter_fc0f33c3`/`.muted_fc0f33c3` can't collide with any other
   component. Tree-shaken if a class is never referenced by counter.html_fc0f33c3. */
.counter_fc0f33c3 {
  display: grid;
  gap: 0.5rem;
  padding: 2rem;
  max-width: 20rem;
}
.muted_fc0f33c3 {
  color: var(--muted, #888);
}
button {
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  cursor: pointer;
}
"
}
