;; core.wat — a CORE (MAIN) module that satisfies the vcsr WASM ABI.
;;
;; THE POINT OF THIS FIXTURE: it is NOT generated by V. It is hand-written
;; WebAssembly text. It could equally be the output of Rust, Zig, C, or
;; AssemblyScript. vcsr's loader/linker contract (docs/WASM-ABI.md) is defined
;; on the wasm *interface* — exports, imports, and how DOM handles cross — not
;; on the source language. Any module that honors the contract below plugs into
;; the same app.js loader and is served by the same vanilla dist/.
;;
;; Conformance (see docs/WASM-ABI.md + tests/phase_07_wasm_linking_test.v):
;;   - kind = MAIN: owns and EXPORTS memory + the indirect function table.
;;   - EXPORTS the shared allocator: __v_alloc / __v_free.
;;   - EXPORTS the uniform route interface: mount / unmount.
;;   - DOM crosses the boundary as `externref` (mount takes the root node as an
;;     externref; the host DOM ops take externref) — never copied through linear
;;     memory.
;;   - the static HTML skeleton lives VERBATIM in the data segment.
;;
;; Recompile with:  wat2wasm core.wat -o core.wasm   (see README.md)

(module $core
  ;; --- the host-call (js FFI) substrate: DOM values cross as externref ---
  ;; (imports must precede owned definitions in the wasm text format)
  ;; register a static HTML skeleton (ptr,len) once -> a host <template> handle.
  (import "env" "register_template" (func $register_template (param i32 i32) (result externref)))
  ;; clone the registered template -> a fresh DOM subtree handle (externref).
  (import "env" "clone_template" (func $clone_template (param externref) (result externref)))

  ;; --- the shared world this MAIN module owns and hands to side modules ---
  (memory (export "memory") 2)
  (table (export "__indirect_function_table") 1 funcref)

  ;; bump-pointer heap; `free` is a no-op (this is a minimal fixture, not a real
  ;; allocator) — the ABI only requires the symbols exist and have these sigs.
  (global $heap (mut i32) (i32.const 1024))

  ;; the static skeleton, embedded in the data segment ("the HTML is in the wasm")
  (data (i32.const 16) "<main class=\"counter_x1\"><h1></h1><button>+1</button></main>")

  (func (export "__v_alloc") (param $n i32) (result i32)
    (local $p i32)
    (local.set $p (global.get $heap))
    (global.set $heap (i32.add (global.get $heap) (local.get $n)))
    (local.get $p))

  (func (export "__v_free") (param $p i32))

  ;; the landing route lives in core; `mount` receives the host root node as an
  ;; externref handle and returns an i32 instance id.
  (func (export "mount") (param $root externref) (result i32)
    (drop (call $register_template (i32.const 16) (i32.const 59)))
    (i32.const 0))

  (func (export "unmount") (param $inst i32)))
